import React, { useState } from 'react';
import { Message, Commitment } from '../../types';
import { Trash2, MoreVertical, Type, Paperclip, Link, Smile, Image, Target } from 'lucide-react';
import { useStore } from '../../store/useStore';

export const DraftComposer: React.FC<{ onCancel: () => void, message: Message, commitment?: Commitment }> = ({ onCancel, message, commitment }) => {
  const [body, setBody] = useState(commitment?.draft_reply || '');
  const { showSnackbar } = useStore();

  const handleSend = () => {
    showSnackbar("Simulation: Email sent via Draft Composer");
    onCancel();
  };

  return (
    <div className="border border-gray-300 rounded-lg overflow-hidden flex flex-col shadow-sm mt-4">
      {/* Header */}
      <div className="bg-gray-50 px-4 py-2 border-b border-gray-200 flex justify-between items-center text-sm">
        <div className="flex items-center text-gray-700">
          <span className="font-medium mr-2">{message.sender_email}</span>
        </div>
      </div>

      {commitment && commitment.draft_reply && (
        <div className="bg-blue-50 px-4 py-1.5 flex items-center text-xs text-blue-700 border-b border-blue-100">
          <Target size={14} className="mr-1.5 text-ai-accent" />
          Draft generated by Commitment Radar
        </div>
      )}

      {/* Body */}
      <textarea 
        className="w-full p-4 min-h-[120px] outline-none resize-none text-gray-800 text-sm"
        value={body}
        onChange={(e) => setBody(e.target.value)}
        placeholder="Reply"
      />

      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-3 bg-white border-t border-gray-200">
        <div className="flex items-center space-x-1">
          <button 
            className="px-6 py-2 bg-gmail-blue text-white rounded-full text-sm font-medium hover:bg-blue-700 transition-colors mr-2 disabled:opacity-50"
            onClick={handleSend}
            disabled={!body.trim()}
          >
            Simulate Send
          </button>
          
          <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-full"><Type size={18} /></button>
          <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-full"><Paperclip size={18} /></button>
          <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-full"><Link size={18} /></button>
          <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-full"><Smile size={18} /></button>
          <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-full"><Image size={18} /></button>
        </div>
        
        <div className="flex items-center space-x-1">
          <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-full"><MoreVertical size={18} /></button>
          <button 
            className="p-2 text-gray-500 hover:bg-gray-100 rounded-full"
            onClick={onCancel}
          >
            <Trash2 size={18} />
          </button>
        </div>
      </div>
    </div>
  );
};
